### ISSUE TITLE
IndexError at main.py

### ISSUE THREAD

**Issue by jpmartins201** [TimChinenov/VaporWaveArt#2]
Hello, I just saw your post about this program of yours and went very curious about it. I was trying to test it but got an error, he looks like this: 

> Traceback (most recent call last):
>   File "main.py", line 255, in <module>
>     eyeDrag(img,eyes)
>   File "main.py", line 205, in eyeDrag
>     img[line:line+drop,eye[0]+itr*strp:eye[0]+itr*strp+strp] = img[line,eye[0]+itr*strp:eye[0]+itr*strp+strp]
> IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

I have all the necessary versions for opencv and python, so I hope you could fix this (or we could check it together another time - very busy now). 
Thanks for the attention!

**Comment by TimChinenov** [comment]
Huh, I haven't seen this error yet. If it's an index error, I'm guessing the "tear" is going too low and trying to leave the page. You can fix this temporarily by reducing the range the random generator in that function goes to (although I really should make a more robust defense).

I know others have been having problems with the eyeDrag function. If problems persist, I am temporarily recommending people simply omit this effect. I'll do my best to repair it at a later time.

**Comment by ZacharyJoswick** [comment]
Getting the same error. Happens on all test images except testface7.png, however, that seems to be due to the eye drag function not being run as the eyes are obscured. I confirmed this with a different picture that also had the eyes obscured and it worked, but another picture of mine with visible eyes caused the exception.

**Comment by TimChinenov** [comment]
Okay, I temporarily removed eyeDrag(), while I figure out a fix. Pushed changes.

**Comment by TimChinenov** [comment]
Okay, I temporarily removed eyeDrag(), while I figure out a fix. Pushed changes.

**Comment by TimChinenov** [comment]
I pushed modifications making sure to type cast all the appropriate values to ints in the eyeDrag() function. Additionally, removed the possibility of the tears pouring out of the image. Let me know if things still do not work.

I have a hunch it might be a version issue. I think I might be using something older
